// react/src/navigation.js
class Navigation extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            activeLink: 3
        };
    }

    render() {
        return (
            <nav className="left-column">
                <ul className="nav-list">
                    {this.props.links.map((link, i) =>
                        <li className={"nav-item " + (this.state.activeLink === i ? "selected" : "")} key={i}>
                            <i className={"nav-icon " + link.icon}></i>
                            <a href={'#' + link.name.toLowerCase()} className="nav-link">{link.name}</a>
                        </li>
                    )}
                </ul>
            </nav>
        )
    }
}

// angular/src/app/navigation/navigation.component.ts
import { Component, Input } from '@angular/core';

@Component({
    selector: 'navigation',
    styleUrls: ['./navigation.component.css'],
    template: `
        <nav class="left-column">
            <ul class="nav-list">
                <li *ngFor="let link of links" [ngClass]="{'selected': isSelected(link) }" class="nav-item" >
                    <i class="nav-icon {{link.icon}}"></i>
                    <a class="nav-link">{{link.name}}</a>
                </li>
            </ul>
        </nav>
    `
})
export class NavigationComponent {
    @Input() links: Array<Object>
    isSelected(link) {
        return link.name === 'Sessions'
    }
}
