// react/src/header.js
class Header extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <header>
                <div className="logo left-column">
                    <img src="../design/cloudMaker-logo-2.png" width="100px"/>
                </div>
                <div className="header-content">
                    <div className="header-company-controls">
                        <i className="fas fa-briefcase"></i>
                        <select>
                            {this.props.companies.map((company, i) =>
                                <option key={i}>{company}</option>
                            )}
                        </select>
                    </div>
                    <div className="header-user-controls">
                        <i className="fas fa-user-circle user-icon"></i>
                        <span>{this.props.user}</span>
                        <i className="fas fa-cog"></i>
                        <i className="fas fa-sign-out-alt"></i>
                    </div>
                </div>
            </header>
        )
    }
}

// angular/src/app/header/header.component.ts
import { Component, Input } from '@angular/core';

@Component({
    selector: 'cm-header',
    styleUrls: ['./header.component.css'],
    // templateUrl: './header.component.html',
    template: `
        <header>
            <div class="logo left-column">
                <img src="assets/cloudMaker-logo-2.png" width="100px"/>
            </div>
            <div class="header-content">
                <div class="header-company-controls">
                    <i class="fas fa-briefcase"></i>
                    <select>
                        <option *ngFor="let company of companies">{{company}}</option>
                    </select>
                </div>
                <div class="header-user-controls">
                    <i class="fas fa-user-circle user-icon"></i>
                    <span>{{user}}</span>
                    <i class="fas fa-cog"></i>
                    <i class="fas fa-sign-out-alt"></i>
                </div>
            </div>
        </header>
    `
})
export class HeaderComponent {
    @Input() companies: Array<Object>
    @Input() user: String
}
